### PR TITLE
fix: switch from moment to dayjs

### LINKED ISSUE #4: Replace moment with dayjs
Moment is unmaintained and has several core bugs in the 2.x release.  The 3.x release is not ready or out yet, and dayjs is the alternative nearly everyone is using now.  If I submit a PR to this package to use dayjs, would you accept and major version bump for us?

### PR DESCRIPTION
**Pull request by niftylettuce**
closes #4

### CODE REVIEW

**Comment by niftylettuce** [comment]
I have temporarily published `@ladjs/simple-recur` until this is merged and you do a new release to npm with it.  Thank you!

**Comment by niftylettuce** [comment]
Please merge, thank you

**Comment by jamiter** [comment]
I'm currently not maintaining this anymore. Maybe @Cliffzz can have a look.

But I think the new Temporal language feature will be the best replacement, once it's in stage 3. See https://github.com/tc39/proposal-temporal.

**Comment by niftylettuce** [comment]
If you gave me npm owner and GitHub access for "niftylettuce" I would gladly help maintain this package.

**Comment by Cliffzz** [comment]
@niftylettuce Thank you for your PR and sorry for the late reply. I've been pretty busy lately with other things. I'm planning to streamline our open source package maintenance in the near future, github actions ci + automatic dependency updates and releases. So that it's easier to maintain and go over open PRs.

Having said that, I don't think changing the `momentjs` dependency to `dayjs` is a good idea. If it ain't broke, don't fix it 😉 Besides that, while I agree there are better options for handling dates than `momentjs`, `momentjs` is still being maintained see: https://github.com/moment/moment/releases

I agree with @jamiter, once the temporal language feature is in stage 3 I plan on rewriting this package using that feature in typescript.

So I will close this PR but feel free to maintain your version using `dayjs`. If you want I can refer `dayjs` users to your fork in the readme.

**Comment by niftylettuce** [comment]
*It IS broken though.*  If you're not aware, there are several core bugs in moment, most of which I've fixed and submitted PR's for... but since moment is no longer maintained... my PR's have gone unmerged.  I wish more people would start listening to me, would make JS a better place.

https://www.theregister.com/2020/08/25/nodejs_dmarc_phishing/
https://www.theregister.com/2020/08/18/nodejs_chromium_patch/

**Comment by Cliffzz** [comment]
Moment might be broken, but that doesn't mean the code in this package is broken... Can you show me what bugs in moment you are talking about? The only PR that I can find that I assume you are referring to is, https://github.com/moment/moment/pull/5145

I might reconsider if the bugs you are referring to have a big negative impact on this module. Otherwise this is an issue with moment and not this module so please discuss it with moment.

**Comment by niftylettuce** [comment]
Moment is no longer maintained, the PR's go untouched and uncommented for years.  Please switch to dayjs, it will only make your project better and more lightweight.

**Pull request closed without merging**
